sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t anyarybalova/docker-ci-react -f Dockerfile.dev .

script:
  - docker run -e CI=true anyarybalova/docker-ci-react npm run test

deploy:
  provider: awselasticbeanstalk
  region: 'us-east-2'
  app: 'docker-ci-react'
  bucket_name: 'elasticbeanstalk-us-east-2-405125346844'
  bucket_path: 'docker-ci-react'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: '$AWS_SECRET_KEY'
